deployment:
  replicaCount: 2

  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::966685100113:role/grafana-lgmt-proxy"

  encryptedValues:
    GRAFANA_CLOUD_PROMETHEUS_ORG_ID: "PLACEHOLDER_ENCRYPT_WITH_STAGE_KEY"
    GRAFANA_CLOUD_LOKI_ORG_ID: "PLACEHOLDER_ENCRYPT_WITH_STAGE_KEY"
    GRAFANA_CLOUD_TEMPO_ORG_ID: "PLACEHOLDER_ENCRYPT_WITH_STAGE_KEY"
    GRAFANA_CLOUD_OTLP_ORG_ID: "PLACEHOLDER_ENCRYPT_WITH_STAGE_KEY"
    GRAFANA_CLOUD_ACCESS_TOKEN: "PLACEHOLDER_ENCRYPT_WITH_STAGE_KEY"

  autoscaling:
    enabled: false

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi
