deployment:
  replicaCount: 1

  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::483945769383:role/grafana-lgmt-proxy"

  encryptedValues:
    GRAFANA_CLOUD_PROMETHEUS_ORG_ID: "PLACEHOLDER_ENCRYPT_WITH_DEV_KEY"
    GRAFANA_CLOUD_LOKI_ORG_ID: "PLACEHOLDER_ENCRYPT_WITH_DEV_KEY"
    GRAFANA_CLOUD_TEMPO_ORG_ID: "PLACEHOLDER_ENCRYPT_WITH_DEV_KEY"
    GRAFANA_CLOUD_OTLP_ORG_ID: "PLACEHOLDER_ENCRYPT_WITH_DEV_KEY"
    GRAFANA_CLOUD_ACCESS_TOKEN: "PLACEHOLDER_ENCRYPT_WITH_DEV_KEY"

  autoscaling:
    enabled: false

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
